import { serializeLevel } from './schema.js';

const HEX_KEYS = new Set(['bgColor', 'color', 'emissive']);

export function exportLevelJson(level) {
  return JSON.stringify(serializeLevel(level), null, 2);
}

export function exportLevelJs(level) {
  const def = serializeLevel(level);
  return `// Generated by Stick Smash Level Editor\n${formatValue(def, 0)}\n`;
}

export function exportLevelModule(level) {
  const def = serializeLevel(level);
  const constName = toConstName(def.id);
  return `// Generated by Stick Smash Level Editor\nexport const ${constName} = ${formatValue(def, 0)};\n`;
}

function formatValue(value, depth, key = '') {
  if (Array.isArray(value)) return formatArray(value, depth);
  if (value && typeof value === 'object') return formatObject(value, depth);
  if (typeof value === 'number') {
    if (HEX_KEYS.has(key)) return `0x${Math.round(value).toString(16).padStart(6, '0')}`;
    if (Number.isInteger(value)) return String(value);
    return String(round(value));
  }
  return JSON.stringify(value);
}

function formatArray(items, depth) {
  if (!items.length) return '[]';
  const pad = indent(depth);
  const inner = indent(depth + 1);
  const simple = items.every(item => item && typeof item === 'object' && !Array.isArray(item));
  if (simple) {
    return `[\n${items.map(item => `${inner}${formatObject(item, depth + 1, true)}`).join(',\n')}\n${pad}]`;
  }
  return `[\n${items.map(item => `${inner}${formatValue(item, depth + 1)}`).join(',\n')}\n${pad}]`;
}

function formatObject(obj, depth, inline = false) {
  const entries = Object.entries(obj).filter(([, value]) => value !== undefined);
  if (!entries.length) return '{}';
  const pad = indent(depth);
  const inner = indent(depth + 1);
  const oneLine = inline && entries.length <= 10 && entries.every(([, value]) => !value || typeof value !== 'object');
  if (oneLine) {
    return `{ ${entries.map(([key, value]) => `${formatKey(key)}: ${formatValue(value, depth + 1, key)}`).join(', ')} }`;
  }
  return `{\n${entries.map(([key, value]) => `${inner}${formatKey(key)}: ${formatValue(value, depth + 1, key)}`).join(',\n')}\n${pad}}`;
}

function formatKey(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function indent(depth) {
  return '  '.repeat(depth);
}

function round(value) {
  return Math.round(value * 1000) / 1000;
}

function toConstName(id) {
  const name = String(id || 'custom_level').toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  return name || 'CUSTOM_LEVEL';
}
